version: '3'
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - '3000:8080'
    environment:
      - DB=<DB_VALUE_GOES_HERE>
# mongodb://localhost:27017/?readPreference=primary&directConnection=true&ssl=false